-- Esquema inicial de Motria.
-- Los nombres de tablas y columnas son los mismos que en el proyecto anterior (demo)
-- para poder reutilizar sus datos si hiciera falta.

CREATE TABLE workshops (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_name VARCHAR(255) NOT NULL,
    owner_name    VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(50),
    address       VARCHAR(255),
    plan          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_workshops_email UNIQUE (email),
    CONSTRAINT ck_workshops_plan CHECK (plan IN ('FREE', 'PRO'))
);

CREATE TABLE authorities (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uk_authorities_name UNIQUE (name)
);

CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255) NOT NULL,
    password             VARCHAR(255) NOT NULL,
    active               BOOLEAN      NOT NULL,
    must_change_password BOOLEAN      NOT NULL,
    workshop_id          BIGINT       NOT NULL REFERENCES workshops (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_authority (
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    authority_id BIGINT NOT NULL REFERENCES authorities (id),
    PRIMARY KEY (user_id, authority_id)
);

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255),
    phone       VARCHAR(50),
    email       VARCHAR(255),
    workshop_id BIGINT       NOT NULL REFERENCES workshops (id),
    created_at  TIMESTAMP(6) NOT NULL
);

CREATE TABLE vehicles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate       VARCHAR(20)  NOT NULL,
    brand       VARCHAR(100),
    model       VARCHAR(100),
    year        INTEGER,
    customer_id BIGINT       NOT NULL REFERENCES customers (id),
    workshop_id BIGINT       NOT NULL REFERENCES workshops (id),
    created_at  TIMESTAMP(6) NOT NULL
);

CREATE TABLE technicals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    specialty   VARCHAR(255),
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    workshop_id BIGINT       NOT NULL REFERENCES workshops (id),
    CONSTRAINT uk_technicals_user UNIQUE (user_id)
);

CREATE TABLE service_orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         TIMESTAMP(6)  NOT NULL,
    vehicle_id   BIGINT        NOT NULL REFERENCES vehicles (id),
    customer_id  BIGINT        NOT NULL REFERENCES customers (id),
    technical_id BIGINT        NOT NULL REFERENCES technicals (id),
    workshop_id  BIGINT        NOT NULL REFERENCES workshops (id),
    diagnosis    VARCHAR(1000),
    status       VARCHAR(20)   NOT NULL,
    CONSTRAINT ck_service_orders_status CHECK (status IN ('PENDIENTE', 'EN_PROCESO', 'TERMINADO'))
);

CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(100) NOT NULL,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMP(6) NOT NULL,
    used       BOOLEAN      NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_password_reset_token UNIQUE (token)
);

-- Casi todas las consultas filtran por taller (multi-tenant).
CREATE INDEX ix_users_workshop          ON users (workshop_id);
CREATE INDEX ix_customers_workshop      ON customers (workshop_id);
CREATE INDEX ix_vehicles_workshop       ON vehicles (workshop_id);
CREATE INDEX ix_vehicles_customer       ON vehicles (customer_id);
CREATE INDEX ix_technicals_workshop     ON technicals (workshop_id);
CREATE INDEX ix_service_orders_workshop ON service_orders (workshop_id, date DESC);
CREATE INDEX ix_service_orders_tech     ON service_orders (technical_id);
